### ISSUE TITLE
AG-1: Add multiple repos to config

### ISSUE THREAD

**Issue by MarkDevOps** [MarkDevOps/AutoGit#1]
Update to be able to iterate over multiple repos via the config file

Config Example
```
org: MarkDevOps
repos:
  AutoGit:
    - dev
    - test
    - uat
    - prod
  AutoGitRepo2:
    - dev
    - test
    - uat
    - prod
```
